version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_nextauth_secret
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - BUCKET=your_bucket_name
      - S3_ACCESS_KEY=your_s3_access_key
      - S3_SECRET_ACCESS_KEY=your_s3_secret_access_key
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
